name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download Athena JDBC Driver
        run: mkdir lib && curl -L -o lib/AthenaJDBC41_2.0.7.jar https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.7/AthenaJDBC41_2.0.7.jar
        shell: bash
      - name: Test (Scala2.12)
        run: sbt -v -Dfile.encoding=UTF-8 ++2.12.14 test
        shell: bash
      - name: Test (Scala2.13)
        run: sbt -v -Dfile.encoding=UTF-8 ++2.13.6 test
        shell: bash
